<?php
// no direct access
	defined('SITE_KEY') or die('File not found');
	
	define ('SHOP_ORDERS_EMAIL', 'matt@siteofhand.com.au');
	define ('SHOP_ORDERS_EMAIL_FROM', 'matt@siteofhand.com.au');
	define ('SHOP_PAYGATE_ERRORS_EMAIL_FROM', 'monitor@siteofhand.com.au');
	define ('SHOP_ORDERS_EMAIL_AS_HTML', 1);
	define ('SHOP_ORDERS_EMAIL_IMAGE', 'site_logo.jpg');
	define ('SHOP_ORDERS_EMAIL_IMAGE_SOURCE', 'embedded');
	define ('SHOP_TIME_ZONE', 'Australia/Sydney');
	define ('SHOP_DISPLAY_ITEM_BROWSER', 1);	
	define ('SHOP_DISPLAY_BREADCRUMB', 0);
	define ('SHOP_DISPLAY_ITEMS_IN_SITEMAP', 1);
	define ('SHOP_ITEM_ALIAS', 'Event');
	define ('SHOP_POST_SIZE_UNITS', 'mm');
	define ('SHOP_POST_WEIGHT_UNITS', 'kg');
	define ('SHOP_POST_CARRIER_ID', 1);
	define ('SHOP_POST_PICKUP', 2232);
	define ('SHOP_POST_DEFAULT_COUNTRY', 'au');
	define ('SHOP_POST_CALC_ROUND_AMOUNT', 1);	
	define ('SHOP_POST_CALC_DEFAULT_ITEM', 1);	
	define ('SHOP_POST_CALC_INPUT_ITEMS_YES', 1);
	define ('SHOP_POST_CALC_INPUT_METHOD_YES', 0);	
	define ('SHOP_POST_CALC_INPUT_PCODE_SIZE', 3);
	define ('SHOP_POST_CALC_INPUT_PCODE_MAX', 4);
	define ('SHOP_POST_CALC_INPUT_ITEMS_MAX', 10);
	define ('SHOP_POST_CALC_SHOW_LOGO', 1);
	define ('SHOP_POST_CALC_HEADING', 'Estimate Postage:');	
	define ('SHOP_POST_CALC_ITEMS_TEXT', 'N# of items:');		
	define ('SHOP_POST_CALC_SUBMIT_TEXT', 'Get Postage Cost');
	define ('SHOP_POST_ETA_ADD_DAYS', 1);	
	define ('SHOP_POST_ADD_AMOUNT', 0);	
	define ('SHOP_POST_ADD_PERCENT', 0);
	define ('SHOP_POST_ALLOW_PICKUP', 1);
	define ('SHOP_POST_PICKUP_ADDRESS', '');	
	define ('SHOP_CART_SIDE_HEADING', 'Your Cart:');
	define ('SHOP_CART_MAIN_HEADING', 'Your Shopping Cart Contains:');
	define ('SHOP_PROMO_MAXLENGTH', 16);
	define ('SHOP_CAN_ENLARGE_ITEM_IMAGE', 1);
	define ('SHOP_LABEL_PRICE', 'Ticket Price:');
	define ('SHOP_LABEL_FOOTER', 'All prices are in Australian Dollars');
	define ('SHOP_HEADING_PAYMENT_CONFIRMED', 'Thank You for your support');	
	define ('SHOP_SUGGEST_ITEM_LIST_HEADING', 'Other Events Available:');
	define ('SHOP_CAT_LIST_HEADING', 'Choose from the following Categories:');
	define ('SHOP_ADD2CART_BUTTON', 'button_BuyNow.jpg');
	define ('SHOP_ADD2CART_BUTTON_DISABLED', 'button_BuyNow_disabled.gif');	
	//define ('SHOP_BUYNOW_TRIGGERS_ALERT', 1);
	define ('SHOP_CHECKOUT_CHECK_READ_RULES', 1);
	define ('SHOP_AMOUNT_TRIGGERS_CAUTION', 500);
	define ('SHOP_CURRENCY_ISO3', 'AUD');	
	define ('SHOP_CURRENCY_SYMBOL_PREFIX', '$');
	define ('SHOP_CURRENCY_SYMBOL_SUFFIX', '');
	define ('SHOP_CHECKOUT_REQ_EMAIL', 1);
	define ('SHOP_CHECKOUT_WITH_HTTPS', 1);
	define ('SHOP_SEND_EMAIL_TO_CUSTOMER', 1);
	define ('SHOP_SEND_EMAIL_TO_MERCHANT', 1);
	define ('SHOP_TIME_OUT_EXPIRY', 30);
	define ('SHOP_ICON_DELETE_IMAGE', 'icon_delete_24x24.png');
	define ('SHOP_IMAGE_RESIZE_MODE', 5);
	define ('SHOP_IMAGE_MAX_WIDTH', 640);
	define ('SHOP_IMAGE_MAX_HEIGHT', 480);
	define ('SHOP_CC_VALIDATE_CARD_EXPIRY_DATE', 1);
	define ('SHOP_CC_FORM_NAME_MAX_LENGTH', 50);
	define ('SHOP_CC_FORM_NUM_MAX_LENGTH', 20);
	define ('SHOP_CC_FORM_NUM_MIN_LENGTH', 16);
	
?>
